script:
    - sh test/test.sh auto
language: php
sudo: true
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
before_install:
 - pip install codecov
after_success:
  - codecov --token=06603794-3714-4948-a0bc-b740621cb59c
