script:
    - sh test/test.sh auto
    - bash test/preinst.sh
language: php
sudo: true
services:
    - mysql
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
